name: code quality

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Python ${{ matrix.python-version}} setup
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version}}

    - name: Dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics